# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-10 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'disciplina',
            },
        ),
        migrations.CreateModel(
            name='Disciplina_Alunos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_disciplina', to='wallapp.Disciplina')),
            ],
            options={
                'db_table': 'disciplina_alunos',
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('titulo', models.CharField(max_length=50)),
                ('texto', models.TextField()),
            ],
            options={
                'db_table': 'mensagem',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('senha', models.TextField()),
                ('nome', models.CharField(blank=True, max_length=250, null=True)),
                ('tipo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.AddField(
            model_name='mensagem',
            name='destinatario',
            field=models.ManyToManyField(related_name='message_destinations', to='wallapp.Usuario'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='remetente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sender_who', to='wallapp.Usuario'),
        ),
        migrations.AddField(
            model_name='disciplina_alunos',
            name='estudante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_estudante', to='wallapp.Usuario'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='professor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_professor', to='wallapp.Usuario'),
        ),
    ]
